In [1]:
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/conda-forge/miniforge/releases/download/23.1.0-1/Mambaforge-23.1.0-1-Linux-x86_64.sh...
📦 Installing...
üìå Adjusting configuration...
ü©π Patching environment...
‚è≤ Done in 0:00:14
🔁 Restarting kernel...


In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
#!conda  list

In [ ]:
!pwd

/mnt/projects-students/LearningDeformations


In [1]:
!conda install -c conda-forge trimesh -y
!conda install -c anaconda h5py -y
!conda install -c conda-forge plyfile -y
!conda install -c anaconda scikit-learn -y
!conda install pytorch torchvision -c pytorch -y
!conda install -c conda-forge glob2 -y
!conda install -c conda-forge torch-scatter -y
!conda install -c conda-forge opencv -y
#!conda install -c open3d-admin open3d -y
!pip install open3d

Solving environment: / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done


==> WARNING: A newer version of conda exists. <==
  current version: 23.1.0
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0



## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - trimesh


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.5.7   |       hbcca054_0         145 KB  conda-forge
    certifi-2023.5.7

In [ ]:
"""!conda remove pytorch torchvision torchaudio cudatoolkit -y

!pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116"""

In [ ]:
#!pip install open3d

In [ ]:
! nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0


In [2]:
!pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

Looking in links: https://download.pytorch.org/whl/cu113/torch_stable.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 GB 624.4 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.3/22.3 MB 55.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 102.7 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 2.0.0
    Uninstalling torch-2.0.0:
      Successfully uninstalled torch-2.0.0
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.15.2a0+072ec57
    Uninstalling torchvision-0.15.2a0+072ec57:
      Successfully uninstalled torchvision-0.15.2a0+072ec57


In [ ]:
#!rm -r /content/drive/MyDrive/dgcnn.pytorch/outputs/yellow_toy_1_2_MSE_trainOnTop

### Run model

In [5]:
%cd /content/drive/MyDrive/dgcnn.pytorch

/content/drive/MyDrive/dgcnn.pytorch


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
!rm -r /content/drive/MyDrive/dgcnn.pytorch/outputs/yellow_toy_1_2

In [6]:
# code from: https://github.com/AnTao97/dgcnn.pytorch#point-cloud-part-segmentation
!python3 main_partseg.py --batch_size=2 --exp_name=yellow_toy_1_2_L1_trainOnTop_6dim_10000 --epochs=10000 --dgcnn_pretrained_model_path="/content/drive/MyDrive/dgcnn.pytorch/pretrained/model.partseg.t7"

Görüntülenen çıkış son 5000 satıra kısaltıldı.
Epoch:  5001 , current epoch train loss:  0.00194485392421484
Epoch:  5002 , current epoch train loss:  0.002227350138127804
Epoch:  5003 , current epoch train loss:  0.002054253127425909
Epoch:  5004 , current epoch train loss:  0.0020063254050910473
Epoch:  5005 , current epoch train loss:  0.0018940767040476203
Epoch:  5006 , current epoch train loss:  0.0019968277774751186
Epoch:  5007 , current epoch train loss:  0.0020454234909266233
Epoch:  5008 , current epoch train loss:  0.0019497566390782595
Epoch:  5009 , current epoch train loss:  0.002001882530748844
Epoch:  5010 , current epoch train loss:  0.001961223315447569
Epoch:  5011 , current epoch train loss:  0.0020609169732779264
Epoch:  5012 , current epoch train loss:  0.0021010811906307936
Epoch:  5013 , current epoch train loss:  0.0021683541126549244
Epoch:  5014 , current epoch train loss:  0.001997290877625346
Epoch:  5015 , current epoch train loss:  0.002076838

### Test

In [7]:
!python3 main_partseg.py --test_batch_size=2 --dgcnn_pretrained_model_path="/content/drive/MyDrive/dgcnn.pytorch/pretrained/model.partseg.t7" --exp_name=yellow_toy_1_2_L1_trainOnTop_6dim_10000 --eval=True  --model_path="/content/drive/MyDrive/dgcnn.pytorch/outputs/yellow_toy_1_2_L1_trainOnTop_6dim_10000/models/model_final.t7" --predicted_pc="/content/drive/MyDrive/dgcnn.pytorch/outputs/yellow_toy_1_2_L1_trainOnTop_6dim_10000/predicted_pointclouds"

Namespace(exp_name='yellow_toy_1_2_L1_trainOnTop_6dim_10000', model='dgcnn', dataset='shapenetpart', class_choice=None, batch_size=32, test_batch_size=2, epochs=200, use_sgd=True, lr=0.001, momentum=0.9, scheduler='cos', no_cuda=False, seed=1, eval=True, num_points=2048, dropout=0.5, emb_dims=1024, k=40, model_path='/content/drive/MyDrive/dgcnn.pytorch/outputs/yellow_toy_1_2_L1_trainOnTop_6dim_10000/models/model_final.t7', visu='', visu_format='ply', predicted_pc='/content/drive/MyDrive/dgcnn.pytorch/outputs/yellow_toy_1_2_L1_trainOnTop_6dim_10000/predicted_pointclouds', dgcnn_pretrained_model_path='/content/drive/MyDrive/dgcnn.pytorch/pretrained/model.partseg.t7')
Using GPU : 0 from 1 devices
/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py:487: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessiv

### Create pointclouds

In [ ]:
inp="/content/drive/MyDrive/data/dataset/YellowToy01/yellow_push_toy_1_70000.obj"
target="/content/drive/MyDrive/data/dataset/YellowToy01/yellow_push_toy_2_70000.obj"
#import torch
#import pytorch3d

In [ ]:
from scipy.spatial import distance
import numpy as np
import trimesh

In [ ]:
pc_inp=trimesh.points.PointCloud(trimesh.load_mesh(inp).vertices[:35000])
pc_inp.export(file_obj="yellow_push_toy_1_35000_points.ply")

pc_target=trimesh.points.PointCloud(trimesh.load_mesh(target).vertices[:35000])
pc_target.export(file_obj="yellow_push_toy_2_35000_points.ply")
euc_dist=distance.cdist(pc_inp.vertices,pc_target.vertices)
min_idx=np.argmin(euc_dist, axis=1)
min_vals=np.min(euc_dist,axis=1)
deformation_dist=np.max(min_vals)
deformation_idx=np.argmax(min_vals)
f=open("yellow_deformation_1_2_35000.txt","w")
f.write("1 2\n")
f.write(str(pc_inp.vertices[deformation_idx])+" "+str(pc_target.vertices[min_idx[deformation_idx]])+"\n")
f.write(str(deformation_idx)+" "+str(min_idx[deformation_idx])+"\n")
f.write(str(pc_target.vertices[min_idx[deformation_idx]]-pc_inp.vertices[deformation_idx])+"\n")
f.write(str(deformation_dist))
f.close()

In [ ]:
f=open("yellow_deformation_1_2_35000.txt","w")
f.write("1 2\n")
f.write(str(pc_inp.vertices[deformation_idx])+" "+str(pc_target.vertices[min_idx[deformation_idx]])+"\n")
f.write(str(deformation_idx)+" "+str(min_idx[deformation_idx])+"\n")
f.write(str(pc_target.vertices[min_idx[deformation_idx]]-pc_inp.vertices[deformation_idx])+"\n")
f.write(str(deformation_dist))
f.close()

In [ ]:
import trimesh
f=open(inp)
samples_inp,face_index_inp,colors_inp=trimesh.sample.sample_surface(trimesh.load_mesh(f,file_type="obj"),35000,sample_color=True)
pc_inp=trimesh.points.PointCloud(samples_inp, colors=colors_inp)
pc_inp.export(file_obj="yellow_push_toy_1_35000_points.ply")

f=open(target)
samples_target,face_index_target,colors_target=trimesh.sample.sample_surface(trimesh.load_mesh(f,file_type="obj"),35000,sample_color=True)
pc_target=trimesh.points.PointCloud(samples_target, colors=colors_inp)
pc_target.export(file_obj="yellow_push_toy_2_35000_points.ply")
euc_dist=distance.cdist(pc_inp.vertices,pc_target.vertices)
min_idx=np.argmin(euc_dist, axis=1)
min_vals=np.min(euc_dist,axis=1)
deformation_dist=np.max(min_vals)
deformation_idx=np.argmax(min_vals)
f=open("yellow_deformation_1_2_35000.txt","w")
f.write("1 2\n")
f.write(str(pc_inp.vertices[deformation_idx])+" "+str(pc_target.vertices[min_idx[deformation_idx]])+"\n")
f.write(str(deformation_idx)+" "+str(min_idx[deformation_idx])+"\n")
f.write(str(pc_target.vertices[min_idx[deformation_idx]]-pc_inp.vertices[deformation_idx])+"\n")
f.write(str(deformation_dist))
f.close()

In [ ]:
import h5py

filename = "data/shapenet_part_seg_hdf5_data/ply_data_train1.h5"

f = h5py.File(filename,'r')
data = f['data'][:].astype('float32')
label = f['label'][:].astype('int64')
seg = f['pid'][:].astype('int64')
f.close()
print(data.shape,label.shape,seg.shape)


[[[-0.0145008  -0.5472554   0.04435405]
  [ 0.01836372  0.27826715 -0.02386446]
  [ 0.01482164 -0.41865438  0.01042023]
  ...
  [ 0.01482164 -0.48505172  0.0385731 ]
  [-0.0145008  -0.24926934  0.06584046]
  [ 0.00656791  0.3903607  -0.05943566]]

 [[-0.05103381  0.11112406 -0.12842704]
  [-0.27297312  0.49021795 -0.3271018 ]
  [-0.18034212  0.49021795  0.46365649]
  ...
  [-0.07147341  0.46562397  0.6983438 ]
  [ 0.1906804   0.49021795  0.23400183]
  [ 0.23412345  0.49598667 -0.07335173]]

 [[-0.49196333 -0.7824724  -0.05577928]
  [-0.61777407 -0.5736105   0.00995999]
  [ 0.32272163  0.38928664 -0.08381004]
  ...
  [ 0.5639905   0.2451422  -0.02105892]
  [ 0.513404    0.38928664 -0.0162586 ]
  [ 0.40939718  0.44893393  0.0110203 ]]

 ...

 [[-0.14831223 -0.3157267   0.10305884]
  [ 0.08609892 -0.04441956 -0.05121949]
  [ 0.24735874  0.23165976  0.47029558]
  ...
  [ 0.12701592  0.03257599  0.09101792]
  [ 0.49982017  0.25839278  0.51284754]
  [ 0.1834425   0.25839278 -0.54290843]]

 [

In [ ]:

print(data.shape,label.shape,seg.shape)

(2048, 2048, 3) (2048, 1) (2048, 2048)


In [ ]:
import numpy as np


In [ ]:
print(seg[0].shape,np.unique(label[0]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
