In [5]:
!conda  list

# packages in environment at /home/unvergozde/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
anyio                     3.7.0              pyhd8ed1ab_1    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h5764c6d_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach             

In [1]:
!pwd

/mnt/projects-students/LearningDeformations


In [6]:
!conda install -c conda-forge trimesh -y
!conda install -c anaconda h5py -y
!conda install -c conda-forge plyfile -y
!conda install -c anaconda scikit-learn -y
!conda install pytorch torchvision -c pytorch -y
!conda install -c conda-forge glob2 -y
!conda install -c conda-forge torch-scatter -y
!conda install -c conda-forge opencv -y
!conda install -c open3d-admin open3d -y
#!pip install open3d

Solving environment: done

## Package Plan ##

  environment location: /home/unvergozde/miniconda3

  added / updated specs:
    - trimesh


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.9.0              |15_linux64_openblas          12 KB  conda-forge
    libcblas-3.9.0             |15_linux64_openblas          12 KB  conda-forge
    libgfortran-ng-13.1.0      |       h69a702a_0          23 KB  conda-forge
    libgfortran5-13.1.0        |       h15d22d2_0         1.4 MB  conda-forge
    liblapack-3.9.0            |15_linux64_openblas          12 KB  conda-forge
    libopenblas-0.3.20         |pthreads_h78a6416_0        10.1 MB  conda-forge
    numpy-1.22.3               |  py310h4ef5377_2         6.8 MB  conda-forge
    trimesh-3.22.1             |     pyhd8ed1ab_0         540 KB  conda-forge
    ------------------------------------------------------------
                  

                                                                                
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done

## Package Plan ##

  environment location: /home/unvergozde/miniconda3

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |         openblas          48 KB  anaconda
    fftw-3.3.9                 |       h27cfd23_1         3.9 MB  anaconda
    joblib-1.1.1               |  py310h06a4308_0         410 KB  anaconda
    scikit-learn-1.2.0         |  py310h6a678d5_1         9.0 MB  anaconda
    scipy-1.7.3                |  py310hac523dd_2        69.2 MB  anaconda
    threadpoolctl-2.2.0        |     pyh0d69192_0          16 KB  anaconda
    ------------------------------------------------------------
                              

libprotobuf-3.20.3   | 2.4 MB    | 9                                     |   3% [A

libpng-1.6.39        | 304 KB    | #######7                              |  21% 


cupti-11.3.1         | 8.0 MB    | 3                                     |   1% 



zstd-1.5.5           | 647 KB    | #####4                                |  15% 




pillow-9.4.0         | 730 KB    | 8                                     |   2% 
ninja-1.10.2         | 8 KB      | ##################################### | 100% 
ninja-1.10.2         | 8 KB      | ##################################### | 100% 





libprotobuf-3.20.3   | 2.4 MB    | #############4                        |  36% 


cupti-11.3.1         | 8.0 MB    | ###7                                  |  10% 






torchvision-0.13.1   | 6.1 MB    |                                       |   0% 








giflib-5.2.1         | 80 KB     | #######3                              |  20% 





libwebp-1.2.4        | 86 KB     | ####################################

magma-2.7.0          | 96.8 MB   | ####9                                 |  13% 







magma-2.7.0          | 96.8 MB   | #####8                                |  16% 
















cudnn-8.2.1          | 865.2 MB  | #6                                    |   4% 







magma-2.7.0          | 96.8 MB   | ######7                               |  18% 






torchvision-0.13.1   | 6.1 MB    | ##################################### | 100% 



















future-0.18.3        | 691 KB    | ##################################### | 100% 
















cudnn-8.2.1          | 865.2 MB  | #8                                    |   5% 



















future-0.18.3        | 691 KB    | ##################################### | 100% 






















 ... (more hidden) ...






















 ... (more hidden) ...


cupti-11.3.1         | 8.0 MB    | ##################################### | 100% 


cupti-11.3.1         | 8.0 MB    | ##################################### | 100% 








magma-2.7.0          | 96.8 MB   | #################################7    |  91% 
















cudnn-8.2.1          | 865.2 MB  | #####8                                |  16% 







magma-2.7.0          | 96.8 MB   | ##################################8   |  94% 
















cudnn-8.2.1          | 865.2 MB  | ######                                |  16% 







magma-2.7.0          | 96.8 MB   | ####################################  |  97% 
















cudnn-8.2.1          | 865.2 MB  | ######1                               |  17% 
















cudnn-8.2.1          | 865.2 MB  | ######3                               |  17% 
















cudnn-8.2.1          | 865.2 MB  | ######5                               |  18% 
















cudnn-8.2.1          | 865.2 MB  | ######7                               |  18% 
















cudnn-8.2.1          | 865.2 MB  | ######8                               |  19% 
















cudnn-8.2.1          | 865.2 MB  | #######      

cudnn-8.2.1          | 865.2 MB  | ###############8                      |  43% 
















cudnn-8.2.1          | 865.2 MB  | ###############9                      |  43% 
















cudnn-8.2.1          | 865.2 MB  | ################1                     |  44% 
















cudnn-8.2.1          | 865.2 MB  | ################2                     |  44% 
















cudnn-8.2.1          | 865.2 MB  | ################4                     |  44% 
















cudnn-8.2.1          | 865.2 MB  | ################5                     |  45% 
















cudnn-8.2.1          | 865.2 MB  | ################7                     |  45% 
















cudnn-8.2.1          | 865.2 MB  | ################8                     |  46% 
















cudnn-8.2.1          | 865.2 MB  | ################9                     |  46% 
















cudnn-8.2.1          | 865.2 MB  | #################1                    |  46% 
















cudnn-8.2.1          | 865.2 M

cudnn-8.2.1          | 865.2 MB  | ########################8             |  67% 
















cudnn-8.2.1          | 865.2 MB  | #########################             |  68% 
















cudnn-8.2.1          | 865.2 MB  | #########################2            |  68% 
















cudnn-8.2.1          | 865.2 MB  | #########################4            |  69% 
















cudnn-8.2.1          | 865.2 MB  | #########################6            |  69% 
















cudnn-8.2.1          | 865.2 MB  | #########################9            |  70% 
















cudnn-8.2.1          | 865.2 MB  | ##########################1           |  71% 
















cudnn-8.2.1          | 865.2 MB  | ##########################6           |  72% 
















cudnn-8.2.1          | 865.2 MB  | ###########################1          |  73% 
















cudnn-8.2.1          | 865.2 MB  | ###########################5          |  75% 
















cudnn-8.2.1          | 865.2 M

                                                                                
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done

## Package Plan ##

  environment location: /home/unvergozde/miniconda3

  added / updated specs:
    - torch-scatter


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |       2_kmp_llvm           6 KB  conda-forge
    libgcc-ng-13.1.0           |       he5830b7_0         758 KB  conda-forge
    libstdcxx-ng-13.1.0        |       hfd8a6a1_0         3.7 MB  conda-forge
    llvm-openmp-14.0.6         |       h9e868ea_0         4.4 MB
    openssl-1.1.1u             |       hd590300_0         1.9 MB  conda-forge
    pytorch-1.13.1             |cpu_py310h92724a6_0        53.5 MB
    torch-scatter-2.1.

xorg-xproto-7.0.31   | 73 KB     |                                       |   0% 

xorg-renderproto-0.1 | 9 KB      |                                       |   0% 


gmp-6.2.1            | 806 KB    |                                       |   0% 



blas-devel-3.9.0     | 12 KB     |                                       |   0% 




p11-kit-0.24.1       | 4.5 MB    |                                       |   0% 





xorg-libxrender-0.9. | 32 KB     |                                       |   0% 






xorg-kbproto-1.0.7   | 27 KB     |                                       |   0% 







glib-2.76.3          | 470 KB    |                                       |   0% 








gstreamer-1.22.0     | 1.9 MB    |                                       |   0% 









libcurl-8.1.2        | 364 KB    |                                       |   0% 










libzlib-1.2.13       | 60 KB     |                                       |   0% 











xorg-xextproto-7.3.0 | 30 KB     |         

libopencv-4.7.0      | 29.1 MB   | ###############                       |  41% 














pulseaudio-client-16 | 735 KB    | ##################################### | 100% 














pulseaudio-client-16 | 735 KB    | ##################################### | 100% 








gstreamer-1.22.0     | 1.9 MB    | ##################################### | 100% 








gstreamer-1.22.0     | 1.9 MB    | ##################################### | 100% 

















xorg-libxfixes-5.0.3 | 18 KB     | ##################################### | 100% 













libopencv-4.7.0      | 29.1 MB   | ###################6                  |  53% 




















keyutils-1.6.1       | 115 KB    | ##################################### | 100% 




















keyutils-1.6.1       | 115 KB    | ##################################### | 100% 






















 ... (more hidden) ...






















 ... (more hidden) ...













libopencv-4.7.0      | 29.1 MB   | ###################

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.

ResolvePackageNotFound: 
  - conda==23.3.1



### Run model

In [ ]:
%cd dgcnn.pytorch

In [31]:
import torch
torch.cuda.current_device()

ImportError: /home/unvergozde/miniconda3/lib/python3.10/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/unvergozde/miniconda3/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

In [15]:
# code from: https://github.com/AnTao97/dgcnn.pytorch#point-cloud-part-segmentation
!python3 main_partseg.py --batch_size=1 --exp_name=blue_toy_1_2

Namespace(exp_name='blue_toy_1_2', model='dgcnn', dataset='shapenetpart', class_choice=None, batch_size=1, test_batch_size=16, epochs=200, use_sgd=True, lr=0.001, momentum=0.9, scheduler='cos', no_cuda=False, seed=1, eval=False, num_points=2048, dropout=0.5, emb_dims=1024, k=40, model_path='', visu='', visu_format='ply')
Using CPU
Let's use 0 GPUs!
Use SGD
Traceback (most recent call last):
  File "/mnt/projects-students/LearningDeformations/dgcnn.pytorch/main_partseg.py", line 457, in <module>
    train(args, io)
  File "/mnt/projects-students/LearningDeformations/dgcnn.pytorch/main_partseg.py", line 227, in train
    seg_pred = model(data, label_one_hot)
  File "/home/unvergozde/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/unvergozde/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs, **kwargs)
  File "/

### Create pointclouds

In [6]:
inp="./data/dataset/BlueToy02/push_toy_1_70000.obj"
target="./data/dataset/BlueToy02/push_toy_2_70000.obj"
#import torch
#import pytorch3d

In [7]:
from scipy.spatial import distance
import numpy as np

In [11]:
"""import trimesh
f=open(inp)
samples_inp,face_index_inp,colors_inp=trimesh.sample.sample_surface(trimesh.load_mesh(f,file_type="obj"),2048,sample_color=True)
pc_inp=trimesh.points.PointCloud(samples_inp, colors=colors_inp)
pc_inp.export(file_obj="yellow_push_toy_1_70000_sampled.ply")

f=open(target)
samples_target,face_index_target,colors_target=trimesh.sample.sample_surface(trimesh.load_mesh(f,file_type="obj"),2048,sample_color=True)
pc_target=trimesh.points.PointCloud(samples_target, colors=colors_inp)
pc_target.export(file_obj="yellow_push_toy_2_70000_sampled.ply")
euc_dist=distance.cdist(pc_inp.vertices,pc_target.vertices)
min_idx=np.argmin(euc_dist, axis=1)
min_vals=np.min(euc_dist,axis=1)
deformation_dist=np.max(min_vals)
deformation_idx=np.argmax(min_vals)
f=open("yellow_deformation_1_2.txt","w")
f.write("1 2\n")
f.write(str(pc_inp.vertices[deformation_idx])+" "+str(pc_target.vertices[min_idx[deformation_idx]])+"\n")
f.write(str(deformation_idx)+" "+str(min_idx[deformation_idx])+"\n")
f.write(str(pc_target.vertices[min_idx[deformation_idx]]-pc_inp.vertices[deformation_idx])+"\n")
f.write(str(deformation_dist))
f.close()"""

b'ply\nformat binary_little_endian 1.0\ncomment https://github.com/mikedh/trimesh\nelement vertex 2048\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\nend_header\nS\x196=\xeb4`=\xba\xfb5>\x15\x80\x94\xff\xb1\xb3\xa9=\xec\xfb\xcf<\xb7o8>\x1f\x81\x91\xff\xe0\xdb\x99<m\xb1\xe8\xbc\x8b\xf4<>\x14\x81\x95\xffq\xecV=\x06&\xfb<k\xeb;>\x15z\x8e\xffk\xd4I\xbcR\xea\x8e\xbc\x89\x0e8>,\x82\x8f\xff\x10zn=\x8b\x1c1<o\'?>9\x83\x90\xffs\x84\x17<\x82~e=Wl6>(\x7f\x90\xff\xd1@\x12=\xa3O)=\xc0o;>\x14s\x85\xff\xc5\xcc\x8e<^\xdd\xe8<\x9bB=>\x06~\x8e\xff\xcbe\xc7=\x82\x89.<\x8f\xa42>\x13\x85\x9a\xff\x12\x1bk=\xc0{W\xbd\x0f\x8a6>+y\x86\xff G\x90=\x92\x89\x13\xbdU\xb19>\x1c}\x90\xff\xdb\x9c\x93=\xf9I)=M<7>\x14l\x80\xff\x98i]=\x8d3\xc4<\xe5m>>%oz\xfff\xf8\x94=\xac\x01P\xbc t=>*\x80\x91\xff\xe4\xe1\xf7\xbbG\xef:\xbd\x03\xd92>\x1dv\x86\xff\xbe\xab\xe3\xbc\x85\xc8\xb8\xbc\x0f\x931>hyg\xff3\x10\xf7\xbc\x93\xe0\x01<\xe5\xbe4>!

In [11]:
import h5py

filename = "data/shapenet_part_seg_hdf5_data/ply_data_train1.h5"

f = h5py.File(filename,'r')
data = f['data'][:].astype('float32')
label = f['label'][:].astype('int64')
seg = f['pid'][:].astype('int64')
f.close()
print(data.shape,label.shape,seg.shape)
    

[[[-0.0145008  -0.5472554   0.04435405]
  [ 0.01836372  0.27826715 -0.02386446]
  [ 0.01482164 -0.41865438  0.01042023]
  ...
  [ 0.01482164 -0.48505172  0.0385731 ]
  [-0.0145008  -0.24926934  0.06584046]
  [ 0.00656791  0.3903607  -0.05943566]]

 [[-0.05103381  0.11112406 -0.12842704]
  [-0.27297312  0.49021795 -0.3271018 ]
  [-0.18034212  0.49021795  0.46365649]
  ...
  [-0.07147341  0.46562397  0.6983438 ]
  [ 0.1906804   0.49021795  0.23400183]
  [ 0.23412345  0.49598667 -0.07335173]]

 [[-0.49196333 -0.7824724  -0.05577928]
  [-0.61777407 -0.5736105   0.00995999]
  [ 0.32272163  0.38928664 -0.08381004]
  ...
  [ 0.5639905   0.2451422  -0.02105892]
  [ 0.513404    0.38928664 -0.0162586 ]
  [ 0.40939718  0.44893393  0.0110203 ]]

 ...

 [[-0.14831223 -0.3157267   0.10305884]
  [ 0.08609892 -0.04441956 -0.05121949]
  [ 0.24735874  0.23165976  0.47029558]
  ...
  [ 0.12701592  0.03257599  0.09101792]
  [ 0.49982017  0.25839278  0.51284754]
  [ 0.1834425   0.25839278 -0.54290843]]

 [

In [24]:

print(data.shape,label.shape,seg.shape)

(2048, 2048, 3) (2048, 1) (2048, 2048)


In [21]:
import numpy as np


In [23]:
print(seg[0].shape,np.unique(label[0]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
