In [59]:
import numpy as np
import open3d as o3d

from utils.reduce_mesh_vertices import pc_to_mesh

Vec2i = o3d.utility.Vector2iVector
Vec3d = o3d.utility.Vector3dVector
Vec3i = o3d.utility.Vector3iVector

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [60]:
point_cloud = o3d.io.read_point_cloud('../data/pointcloud_sampled/YellowToy01/targets/deformed_2_correspondences_zoom_2048.ply')
mesh = o3d.io.read_triangle_mesh('../data/dataset/YellowToy01/yellow_push_toy_2.obj')

In [61]:
pc_to_mesh(mesh, point_cloud)

TriangleMesh with 2048 points and 452499 triangles, and textures of size (8192, 8192) 

In [62]:
print(np.asarray(mesh.vertices))
print(np.asarray(point_cloud.points))
assert np.all(np.asarray(mesh.vertices) == np.asarray(point_cloud.points))

[[-0.061859 -0.102731  0.05959 ]
 [-0.027609 -0.061958  0.039002]
 [-0.059253 -0.046462  0.011552]
 ...
 [-0.020132 -0.079436  0.012178]
 [-0.039367 -0.053278  0.045449]
 [-0.089319 -0.074494  0.013959]]
[[-0.061859 -0.102731  0.05959 ]
 [-0.027609 -0.061958  0.039002]
 [-0.059253 -0.046462  0.011552]
 ...
 [-0.020132 -0.079436  0.012178]
 [-0.039367 -0.053278  0.045449]
 [-0.089319 -0.074494  0.013959]]


In [63]:
cloud_points = np.asarray(point_cloud.points).copy()
cloud_points += np.array([0.08, 0, 0])
mesh_points = np.asarray(mesh.vertices).copy()

pc_copy = o3d.geometry.PointCloud(Vec3d(cloud_points))

assert len(cloud_points) == len(mesh_points)
points = np.concatenate([cloud_points, mesh_points])
lines = np.arange(len(cloud_points))
lines = np.stack([lines, lines + len(lines)], axis=1)
print(lines)
line_set = o3d.geometry.LineSet(Vec3d(points), Vec2i(lines))

o3d.visualization.draw_geometries([mesh, pc_copy, line_set])


[[   0 2048]
 [   1 2049]
 [   2 2050]
 ...
 [2045 4093]
 [2046 4094]
 [2047 4095]]


In [70]:
point_cloud_1 = o3d.io.read_point_cloud('../data/pointcloud_sampled/YellowToy01/inputs/non_deformed_2_correspondences_zoom_2048.ply')
mesh_1 = o3d.io.read_triangle_mesh('../data/dataset/YellowToy01/yellow_push_toy_1.obj')
point_cloud_2 = o3d.io.read_point_cloud('../data/pointcloud_sampled/YellowToy01/targets/deformed_2_correspondences_zoom_2048.ply')
mesh_2 = o3d.io.read_triangle_mesh('../data/dataset/YellowToy01/yellow_push_toy_2.obj')

mesh_1 = pc_to_mesh(mesh_1, point_cloud_1)
mesh_2 = pc_to_mesh(mesh_2, point_cloud_2)

mesh_2_points = np.asarray(mesh_2.vertices)
mesh_2_points += np.array([0.08, 0, 0])
points = Vec3d(np.concatenate([
    np.asarray(mesh_1.vertices),
    mesh_2_points
]))
lines = Vec2i(np.arange(len(points)).reshape(2, -1).T)
line_set = o3d.geometry.LineSet(points, lines)

o3d.visualization.draw_geometries([mesh_1, mesh_2, line_set])